describe('Enviar mensagem', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/login')
    cy.get('[name="email"]').type('adotante@adotante.com')
    cy.get('[name="password"]').type('adotante')
    cy.get('.sc-a06d05ba-0').click()
    cy.get('a > .sc-a06d05ba-0').eq(1).click()
    cy.contains('Entrar em contato com o dono').click()
    cy.get('.sc-679b4dca-7').click().type('Oi, gostaria de adotar o seu animal!')
    cy.get('.sc-679b4dca-8 > svg').click()
    cy.get('.sc-679b4dca-3').should('contain.text', 'Oi, gostaria de adotar o seu animal!')
    cy.get('.sc-368028a3-5 > .sc-b85c88e3-0 > :nth-child(6)').click()
    cy.get('[name="email"]').type('doador@doador.com')
    cy.get('[name="password"]').type('doadoraf')
    cy.get('.sc-a06d05ba-0').click()
    cy.get('.sc-368028a3-5 > .sc-b85c88e3-0 > [href="/area_logada/conversas"] > .sc-b85c88e3-1').click()
    cy.get('.sc-ed493da-3').should('contain.text', 'Oi, gostaria de adotar o seu animal!')
  })
})